global using BlazorComponent;
global using Masa.Blazor;
global using Masa.Blazor.Presets;
global using FunionBlazor.Application;
global using FunionBlazor.Application.Dto;
global using FunionBlazor.Web.Core.Data;
global using Microsoft.AspNetCore.Components;
global using Microsoft.JSInterop;
global using System.Linq;